#!/bin/bash

# exit on error
set -e

# Find the branch and any release designation
sha=$(git rev-parse HEAD)
branch=$(git branch -v --no-abbrev  | \
         fgrep "$sha" | \
         grep -v detached | \
         awk '{print $1}')
release=$(echo $branch | sed -e 's|release/||')

echo branch is "$branch", release is $release

if echo $branch | egrep '^release/.*' > /dev/null; then
  echo "Adding remote"
  git remote add github \
    https://pbors:${GH_TOKEN}@github.com/pallet/lein-set-version.git
  echo "Pushing to master"
  git push github HEAD:master > /dev/null 2>&1 || exit 1
  echo "Tagging"
  git tag $release || exit 1
  echo "Pushing tags"
  git push github --tags > /dev/null 2>&1 || exit 1
  echo "Updating version"
  lein2 set-version :point || exit 1
  echo "Commiting version change"
  git add -u && \
  git config --global user.email "hugo@palletops.com" && \
  git config --global user.name "Hugo Duncan" && \
  git commit -m "Updated version for next release cycle" && \
  echo "Pushing to develop" && \
  git push github HEAD:develop > /dev/null 2>&1 || exit 1
fi
